spring:
  datasource:
    url: jdbc:postgresql://localhost/postgresql-metric1-60905
    username: goto
    password: runedi4149
    driverClassName: org.postgresql.Driver
  thymeleaf:
    cache: false
  session:
    store-type:jdbc
