spring:
  datasource:
    url: jdbc:postgresql://localhost/postgresql-metric1-60905-test
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  thymeleaf:
    cache: false
  session:
    store-type:jdbc
  messages:
    basename: ValidationMessages
  profiles:
    active: unit

